### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by emillon** [mirage/ca-certs#1]
Hi,

We should support what "common" linux distributions use. As a data point [here is a list of locations checked by go](https://golang.org/src/crypto/x509/root_linux.go).

### :clipboard: Distributions checked for `dune build @runtest-e2e`

(names are the ocaml/opam2 distro names)
- [x] debian
- [ ] alpine: works but see #5
- [x] centos (7)
- [ ] oraclelinux: missing a depext for tls depext
- [x] opensuse
- [x] fedora
- [x] ubuntu
- [x] ubuntu-lts

**Comment by hannesm** [comment]
I'll close this issue, and await reports on distributions where this package does not work as expected (ocaml-ci and opam-ci have positive reports that this package works on their distributions).
