### ISSUE TITLE
Failure  ca-certs: empty trust anchors macOs Big Sur

### ISSUE THREAD

**Issue by matheussbernardo** [mirage/ca-certs#13]
Fatal error: exception (Failure
   "ca-certs: empty trust anchors.\
  \nPlease report an issue at https://github.com/mirage/ca-certs, including:\
  \n- the output of uname -s\
  \n- the distribution you use\
  \n- the location of default trust anchors (if known)\
  \n")

When I am tryng to use Cohttp-lwt-unix I got this error

this command security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain
returns a lot of certs

**Comment by hannesm** [comment]
Thanks for your report. This is unexpected. If you clone this repository and execute `dune runtest`, does it run successfully? Unfortunately I don't have shell access to "macOs Big Sur".

**Comment by patricoferris** [comment]
Hi @hannesm and @matheussbernardo,

I was trying to recreate this issue and ran the following after cloning the main branch of this repository (commit `00491224306525c50e020831e7385c10ba3287c1`): 

```
opam switch create 4.11.2 4.11.2
opam pin add -yn .
opam depext -y ca-certs
opam install -ty ca-certs --deps-only
dune runtest
```

All the tests pass, for full transparency here is the output of `dune runtest`. 

```
    ocamlopt test/tests.exe
ld: warning: directory not found for option '-L/opt/local/lib'
ld: warning: directory not found for option '-L/opt/homebrew/lib'
       tests alias test/runtest
Testing `verification tests'.
This run has ID `B3B64879-8BEA-480E-AB96-152291B191D6'.

  [OK]          X509 certificate validation          0   google.com.
  [OK]          X509 certificate validation          1   extended-validation....
  [OK]          X509 certificate validation          2   self-signed.badssl.com.
  [OK]          X509 certificate validation          3   expired.badssl.com.
  [OK]          X509 certificate validation          4   untrusted-root.badss...
  [OK]          X509 certificate validation          5   wrong.host.badssl.com.
  [OK]          X509 certificate validation          6   incomplete-chain.bad...
  [OK]          X509 certificate validation          7   sha1-intermediate.ba...
  [OK]          X509 certificate validation          8   wrong.host.google.com.

Full test results in `~/ca-certs/_build/default/test/_build/_tests/verification tests'.
Test Successful in 0.002s. 9 tests run.
```

The relevant environment information is: 

```
sw_vers -productVersion
11.0.1
opam --version
2.0.8
uname -m
x86_64
```

@matheussbernardo is there any additional information such as the version of Big Sur, architecture etc. that you can pass on to pin-point this potential bug? Thanks.

**Comment by matheussbernardo** [comment]
Sorry I think. I did not have installed the tls library. Probably that was the cause of the problem.

**Comment by hannesm** [comment]
ok, thanks for testing and your report. I'll close this issue -- if someone figures why the exception was raised (and how to avoid it in this case), please report.
