### ISSUE TITLE
Support NIX_SSL_CERT_FILE for a build time trust anchor

### ISSUE THREAD

**Issue by sternenseemann** [mirage/ca-certs#16]
NixOS generally install as global ca bundle to `/etc/ssl/certs/ca-bundle.crt`, so in general `ca-certs` works as expected. However test suites are executed in a sandboxed environment where this path does not exist which currently means that we can't run the `cohttp-lwt-unix` test suite.

However, the nix builder environment sets two environment variables if we depend on the ca bundle explicitly. For example:

```
SSL_CERT_FILE=/nix/store/68bpd4p659sm50lb615djysx2znnw4xm-nss-cacert-3.60/etc/ssl/certs/ca-bundle.crt
NIX_SSL_CERT_FILE=/nix/store/68bpd4p659sm50lb615djysx2znnw4xm-nss-cacert-3.60/etc/ssl/certs/ca-bundle.crt
```

It'd be nice if we could support an environment variable like `SSL_CERT_FILE`. This would also be helpful in other situations to override the default bundle location.

**Comment by sternenseemann** [comment]
> I know that "trust anchor" is not defined by POSIX (sadly), so every Unix (and each Linux distribution) decides on a different place [and AFAICT there's neither a system call or environment variable standardised].
> 
> How should the solution on NixOS in your opinion look like? Is the `SSL_CERT_FILE` always specified? How is NixOS uniquely determined (I wouldn't like the build / test to fail if on another Linux someone set the environment variable `SSL_CERT_FILE`) -- can this be achieved from the output of `uname`?

I've checked a bit more precisely now and can explain this a bit better: NixOS generally has the global trust anchor in a somewhat standard position. However to ensure build purity and reproducibility the global trust anchor is not available, but if you add `cacert` to your build dependencies, nix will run [its setup hook](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/misc/cacert/setup-hook.sh) which sets `NIX_SSL_CERT_FILE`.

This is only done at build time and on a normal system these environment variables are not present.

With `SSL_CERT_FILE` being deprecated, I'd say the ideal solution would be to check if `NIX_SSL_CERT_FILE` is set and use it if present. If you are worried about overriding at runtime you could also just check for that if you don't find any global trust anchors.

> How does e.g. curl do this on NixOS? How does "go" do it (as far as I can tell https://golang.org/src/crypto/x509/root_linux.go does not read environment variables)?

[go is patched](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/go/ssl-cert-file-1.16.patch) which may also provide a reference for an implementation in `ca-certs`. `curl` seems to [use `SSL_CERT_FILE`](https://github.com/curl/curl/blob/f073a427b4fcab111b3728935f8beb3a19de10f0/src/tool_operate.c#L2487)

**Comment by hannesm** [comment]
would https://github.com/mirage/ca-certs/pull/17 be fine for your use case? this respects the NIX_SSL_CERT_FILE environment variable (expects a _single_ path to a file!) by using it if set (on Linux).
