### ISSUE TITLE
Release to opam

### ISSUE THREAD

**Issue by aronerben** [mirage/ca-certs#6]
Could this package please be released to opam?

**Comment by dinosaure** [comment]
I think we are ready for a release according to #7. The API change a bit so can you give to us any feedbacks on the PR?

**Comment by aronerben** [comment]
Thank you for the update and the work, I've added my comment directly into the PR :)

**Comment by hannesm** [comment]
done in https://github.com/ocaml/opam-repository/pull/17384

**Comment by aronerben** [comment]
Thank you!

**Comment by hannesm** [comment]
it is now PRed to opam-repository at https://github.com/ocaml/opam-repository/pull/17391 again -- this time with a test suite that works fine with an opam sandbox :)
